// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-riddle.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
import { getRiddle, getTotalRiddleCount, isPremiumLevel } from "npm:@/lib/riddlesDatabase";
var get_riddle_default = defineTool({
  name: "get_riddle",
  title: "Get riddle by level",
  description: "Fetch the bilingual (Telugu + English) riddle for a given game level, including its hint and difficulty. The answer is never included.",
  inputSchema: {
    level: z.number().int().min(1).describe("Game level number, starting at 1.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ level }) => {
    const total = getTotalRiddleCount();
    if (level > total) {
      return {
        content: [{ type: "text", text: `Level ${level} does not exist. Levels run from 1 to ${total}.` }],
        isError: true
      };
    }
    const riddle = getRiddle(level);
    const payload = {
      level,
      telugu: riddle.telugu,
      english: riddle.english,
      hint: riddle.hint,
      difficulty: riddle.difficulty,
      premium: isPremiumLevel(riddle.id)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-riddles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
import riddlesData, { getTotalRiddleCount as getTotalRiddleCount2, isPremiumLevel as isPremiumLevel2 } from "npm:@/lib/riddlesDatabase";
var search_riddles_default = defineTool2({
  name: "search_riddles",
  title: "Search riddles",
  description: "Search the riddle collection by keyword (matches the English or Telugu riddle text and the hint) and optionally by difficulty. Answers are never included.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Keyword or phrase to search for."),
    difficulty: z2.enum(["easy", "medium", "hard", "expert", "genius"]).nullable().describe("Optional difficulty filter. Use null for all difficulties."),
    limit: z2.number().int().min(1).max(50).describe("Maximum number of riddles to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, difficulty, limit }) => {
    const needle = query.toLowerCase();
    const matches = riddlesData.filter((r) => difficulty ? r.difficulty === difficulty : true).filter(
      (r) => r.english.toLowerCase().includes(needle) || r.telugu.includes(query) || r.hint.toLowerCase().includes(needle)
    ).slice(0, limit).map((r) => ({
      level: r.id,
      telugu: r.telugu,
      english: r.english,
      hint: r.hint,
      difficulty: r.difficulty,
      premium: isPremiumLevel2(r.id)
    }));
    const payload = { total: getTotalRiddleCount2(), matchCount: matches.length, riddles: matches };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/check-answer.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { getRiddle as getRiddle2, getTotalRiddleCount as getTotalRiddleCount3 } from "npm:@/lib/riddlesDatabase";
var check_answer_default = defineTool3({
  name: "check_answer",
  title: "Check a riddle answer",
  description: "Check whether a guess solves the riddle at a given level. Returns whether it is correct plus the riddle's hint; it never reveals the answer.",
  inputSchema: {
    level: z3.number().int().min(1).describe("Game level number of the riddle being answered."),
    guess: z3.string().trim().min(1).describe("The proposed answer, in English or Telugu.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ level, guess }) => {
    const total = getTotalRiddleCount3();
    if (level > total) {
      return {
        content: [{ type: "text", text: `Level ${level} does not exist. Levels run from 1 to ${total}.` }],
        isError: true
      };
    }
    const riddle = getRiddle2(level);
    const normalized = guess.toLowerCase().trim();
    const correct = riddle.answer.some((a) => normalized.includes(a.toLowerCase()));
    const payload = { level, guess, correct, hint: riddle.hint };
    return {
      content: [
        {
          type: "text",
          text: correct ? `Correct! "${guess}" solves level ${level}.` : `Not quite. Hint for level ${level}: ${riddle.hint}`
        }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-riddle-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import riddlesData2, { getTotalRiddleCount as getTotalRiddleCount4, getPremiumRiddleCount } from "npm:@/lib/riddlesDatabase";
var get_riddle_stats_default = defineTool4({
  name: "get_riddle_stats",
  title: "Get riddle collection stats",
  description: "Return the total number of riddles, how many are premium, and the count of riddles per difficulty tier.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const byDifficulty = riddlesData2.reduce((acc, r) => {
      acc[r.difficulty] = (acc[r.difficulty] ?? 0) + 1;
      return acc;
    }, {});
    const payload = {
      totalRiddles: getTotalRiddleCount4(),
      premiumRiddles: getPremiumRiddleCount(),
      byDifficulty
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tenali-rama-s-riddle-quest",
  title: "Tenali Rama's Riddle Quest",
  version: "0.1.0",
  instructions: "Tools for Tenali Rama's Riddle Quest, a bilingual (Telugu + English) riddle game. Use `get_riddle` to fetch a level's riddle, `search_riddles` to find riddles by keyword or difficulty, `check_answer` to test a guess, and `get_riddle_stats` for collection totals. Answers are never revealed.",
  tools: [get_riddle_default, search_riddles_default, check_answer_default, get_riddle_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
